<?php
/**
 * http://www.uyan.cc/help/html/uyan-diy
 */

/**
 * Implements hook_menu().
 */
function uyan_menu() {
	$items = array();
	$items['admin/config/content/uyan_comments'] = array(
		'title' => 'Uyan comment settings',
    'description' => 'Uyan comments on site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uyan_comments_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'uyan.admin.inc',
	);
	return $items;
}

/**
 * Implements hook_node_view().
 */
function uyan_node_view($node, $view_mode, $langcode) {
	$uyan_comments_node_types = variable_get('uyan_comments_node_types', array());
	if($view_mode == 'full' && in_array($node->type, $uyan_comments_node_types)) {
		unset($node->content['comments']);
    $node->content['uyan'] = array(
      '#weight' => 500,
      '#markup' => uyan_comment_blocks(),
    );
		// drupal_add_js("jQuery(document).ready(function ($) { $('#node-".$node->nid."').append('<div id=\"uyan_frame\"></div>'); });",array('type' => 'inline', 'scope' => 'footer', 'weight' => 400));
		drupal_add_js('http://v2.uyan.cc/code/uyan.js?uid='.variable_get('uyan_account_id', '91212'),array('type' => 'external', 'scope' => 'footer', 'weight' => 500));
	}
}

/**
 * Implements hook_block_info().
 * //评论热榜
 * //最新评论
 */
function uyan_block_info() {
	$blocks = array();
  $blocks['uyan_all_comment'] = array(
      'info' => t('UYAN COMMENT'),
  );
  $blocks['uyan_hot_comment'] = array(
      'info' => t('UYAN HOT COMMENT'),
  );
  $blocks['uyan_new_comment'] = array(
      'info' => t('UYAN NEW COMMENT'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function uyan_block_view($delta = '') {
	$block = array();
  switch ($delta) {
    case 'uyan_all_comment':
      $block['subject'] = t('UYAN COMMENT');
      $block['content'] = uyan_comment_blocks('uyan_frame');
      break;
    case 'uyan_hot_comment':
      $block['subject'] = t('UYAN HOT COMMENT');
      $block['content'] = uyan_comment_blocks('hotcmt_unit');
      break;
    case 'uyan_new_comment':
      $block['subject'] = t('UYAN NEW COMMENT');
      $block['content'] = uyan_comment_blocks('newcmt_unit');
      break;
  }
  return $block;
}

function uyan_comment_blocks($type = 'uyan_frame') {
	return '<div id="'.$type.'"></div>';
}
