<?php
//
/**
 * Implements hook_menu().
 */
function mp_service_menu() {
  $items['mp_service'] = array(
    'title' => 'valid&response',
    'page callback' => 'mp_service_response',
    'access callback' => TRUE,
  );
  $items['mp_service/%user/%'] = array(
    'title' => 'valid&response',
    'page callback' => 'wx_response',
    'page arguments' => array(1,2),//$user->id,$wx_mp_id
    'access callback' => TRUE,
  );
  $items['admin/config/mp_service'] = array(
    'title' => 'mp_service settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_service_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mp_service.admin.inc',
  );
  return $items;
}

function wx_response($user, $wx_mp_id = 'gh_a1f2569abd7f') {
  module_load_include('php', 'mp_service', 'wechat.class');
  $options = array(
    'token'=> $wx_mp_id, //填写你设定的key
  );
  $weObj = new Wechat($options);
  $weObj->valid();
  $type = $weObj->getRev()->getRevType();
  switch($type) {
      case Wechat::MSGTYPE_TEXT:
        $weObj->text("hello, I'm wechat")->reply();
        exit;
        break;
      case Wechat::MSGTYPE_EVENT:
        $weObj->text("您好，欢迎关注癌症新视角，\n爱喜与您一起，探讨21世纪最伟大的话题！")->reply();
        break;
      case Wechat::MSGTYPE_IMAGE:
        $weObj->text("暂时不支持图片响应！")->reply();
        break;
      default:
        $weObj->text("这是什么？")->reply();
  }

}

function mp_service_response() {
  module_load_include('inc', 'mp_service', 'mp_service_adv');
  $options = array(
    'token'=> variable_get('mp_service_token', 'ybzx'),//填写你设定的key
  );
  $options = array(
    'token'=>'ybzx',
    'account'=>'xiangkeguo@gmail.com',
    'password'=>'mjk5nj'
  );
  $wechatObj = new Wechat($options);
  // $wechatObj->valid(); //注意, 应用验证通过后,可将此句注释掉, 但会降低网站安全性
  $type = $wechatObj->getRev()->getRevType();
  switch($type) {
    case Wechat::MSGTYPE_TEXT:
      $keyword =  trim($wechatObj->getRevContent());
      $keyword = strtolower($keyword);
      $FromUserName =  $wechatObj->getRev()->getRevFrom();
      if(!mp_service_get_record($FromUserName)) {
        mp_service_add_user($FromUserName,$last_cmd='old_user');
      }
      $uid = mp_service_get_uid_by_name($FromUserName);
      //http://betternewlife.u.qiniudn.com/newlife-01.mp3
      //default msg
      $contentStr = "【52】广播\n【110】推荐给好友？\n【5010】灵命日粮文字版new\n广播指令为纯数字，请勿带*号。号和中括号\n以后再有什么问题，回复【11+您的祝福与感恩或建议内容】呼唤小永吧！";
      //【1】玩法介绍\n【2】发布相片/心情\n【3】查看活跃用户\n【4】每日灵修广播\n
      if($uid) {
        $mp_service_records = mp_service_get_record($FromUserName);
        // watchdog('mp_service_records', '<pre>'.print_r($mp_service_records,TRUE), array(), WATCHDOG_NOTICE, 'link');
        //15秒内回复任何字符都拒绝！
        if($keyword != '88' && $mp_service_records['last_cmd'] == '20' && (REQUEST_TIME - $mp_service_records['last_cmd_timestamp'] < 900)) {
          $contentStr = "请选择要发布的相片!\n回复【88】取消改指令！";
          $wechatObj->text($contentStr)->reply();
          exit;
        }
      }
      //以20开头的，发布内如的，如果没有绑定，直接回绝！
      if(substr($keyword, 0,2) == '20' && substr($keyword, 0,6) != '201314'  ) {
        if(!$uid) {
          $contentStr = "未绑定！不可发送20开头的指令！\n回复【9】查看绑定帮助\n回复【5】良友今日广播";
          $wechatObj->text($contentStr)->reply();
          exit;
        }
      }
      $prefix_uri = 'http://audio2.liangyou.net/files/media/program_live/';
      // $prefix_uri = 'http://liangyou.nissigz.com/media/';
      // $prefix_uri = 'http://liangyou2.nissigz.com:15200/';
      // http://liangyou2.nissigz.com:15200/gv/gv131218.mp3
       $radio_list = array(
                '500' => 'ws',
                '501' => 'bv',
                '502' => 'ee',
                '503' => 'se',
                '504' => 'bf',
                '505' => 'up',
                '506' => 'hg',
                '507' => 'bc',
                '508' => 'ds',
                '509' => 'gv',
                '523' => 'gv',
                );
$notice = "\n
【cw】齐来颂扬*new*
【be】真道分解*new*
【ns】生命的四季*new*
【tr】彩虹桥*New*
----新年快乐----
永不止息，需要有你!
回复【31】【32】\n回复【201314+新年愿望】去微信大屏幕看看吧！\n
<a href='http://stream.liangyou.net/channel/65837e3587'>同行频道（串流广播）</a>";//回复【11+您的祝福与感恩或建议内容】


      $radio_list_simple = array(
        // 福音节目-适合所有人士
        '31' => array(
          'ir' => 'i-radio爱广播',//0
          'eg' => '英语世界',//2
          'gt' => '恩典与真理', //0
          'wa' => '天路导向',//6,7
          // 'cwa' => '天路导向（粤）',//6,7
          'bg' => '普世佳音',//1
          'yu' => '绝妙当家',//0
          'gv' => '生活无国界',//0
          'zz' => '零点零距离',//1-5
          'se' => '恋爱季节',//1-5
          'up' => '亲情不断电',//1-5
          'bc' => '书香园地',//1-5
          'gn' => '现代人的希望',//0
          'hg' => '欢乐卡恰碰',//0
          'yn' => '爱在人间（云南）',//0
          'im' => 'i关怀心磁场',//1-5
          'ib' => '无限飞行号',//0
          'rt' => '今夜心未眠',//6,7
          'em' => '听听90后',//6,7
          'yr' => 'Yi-radio爱广播',//0
          ),
        '32' => array(
          // 栽培节目-适合基督徒

          'bv' => '灵命日粮',
          'ee' => '拥抱每一天',
          'bf' => '幸福满家园',
          'ws' => '长夜的牵引',
          'be' => '真道分解',
          'tr' => '彩虹桥',
          'ns' => '生命的四季',
          'cw' => '齐来颂扬',
          // 
          // 'bv' => '空中辅导',
          // 'bv' => '无愧的工人',
          // 'bv' => '有问必答',
          // 'bv' => '生命指南针',
          // 'bv' => '蓝天绿洲',
          // 'bv' => '圣乐天地 ',
          // 'bv' => '好牧人',
          // 'bv' => '善牧良言',
          // 'bv' => '经动人心',
          // 'bv' => '信仰百宝箱',
          // 'bv' => '生命的福音',
          // 'bv' => '听听女人心',
          // 'bv' => '生根建造',
          // 'bv' => '聆听主道',
          // 'bv' => '圣言盛宴',
          // 'bv' => '真理之光',
          // 'bv' => '圣乐天地 - 古典圣诗',
          // 'bv' => '空中崇拜',
          // 'bv' => '给力人生',
          // 'bv' => '空中门训',
          // 'bv' => '生活之光',
          ),
        // 'nissigz3' = array(
        //  // 训练节目-适合事奉人员
        //  // 接棒人
        //  // 晨曦讲座
        //  // 申命记
        //  // 教牧辅导
        //  // 事奉装备
        //  // 基督教教义
        //  // 基督教伦理学
        //  // 圣诞节特辑
        //  // 新约神学
        //  ),

        );



      $prefix['31'] = 'http://liangyou2.nissigz.com:15200/';
      $prefix['32'] = 'http://liangyou.nissigz.com:18100/';
      $radios_list = array(
        // 福音节目-适合所有人士
        // '31' => array(//15200
          'ir' => array('name' =>'i-radio爱广播', 'prefix'=>$prefix['31'],'day'=>0),//0
          'eg' => array('name' =>'英语世界', 'prefix'=>$prefix['31'],'day'=>2),//2
          'gt' => array('name' =>'恩典与真理', 'prefix'=>$prefix['31'],'day'=>0),//0
          'wa' => array('name' =>'天路导向', 'prefix'=>$prefix['31'],'day'=>6),//6,7
          'cwa' => array('name' =>'天路导向（粤）', 'prefix'=>$prefix['31'],'day'=>6),//6,7
          'bg' => array('name' =>'普世佳音', 'prefix'=>$prefix['31'],'day'=>1),//1
          'yu' => array('name' =>'绝妙当家', 'prefix'=>$prefix['31'],'day'=>0),//0
          'gv' => array('name' =>'生活无国界', 'prefix'=>$prefix['31'],'day'=>0),//0
          'zz' => array('name' =>'零点零距离', 'prefix'=>$prefix['31'],'day'=>5),//1-5
          'se' => array('name' =>'恋爱季节', 'prefix'=>$prefix['31'],'day'=>5),//1-5
          'up' => array('name' =>'亲情不断电', 'prefix'=>$prefix['31'],'day'=>5),//1-5
          'bc' => array('name' =>'书香园地', 'prefix'=>$prefix['31'],'day'=>5),//1-5
          'gn' => array('name' =>'现代人的希望', 'prefix'=>$prefix['31'],'day'=>0),//0
          'hg' => array('name' =>'欢乐卡恰碰', 'prefix'=>$prefix['31'],'day'=>0),//0
          'yn' => array('name' =>'爱在人间（云南）', 'prefix'=>$prefix['31'],'day'=>0),//0
          'im' => array('name' =>'i关怀心磁场', 'prefix'=>$prefix['31'],'day'=>5),//1-5
          'ib' => array('name' =>'无限飞行号', 'prefix'=>$prefix['31'],'day'=>0),//0
          'rt' => array('name' =>'今夜心未眠', 'prefix'=>$prefix['31'],'day'=>6),//6,7
          'em' => array('name' =>'听听90后', 'prefix'=>$prefix['31'],'day'=>6),//6,7
          'yr' => array('name' =>'Yi-radio爱广播', 'prefix'=>$prefix['31'],'day'=>0),//0
          
        // '32' => array(//18100
          // 栽培节目-适合基督徒
          'bv' => array('name' =>'灵命日粮', 'prefix'=>$prefix['32'],'day'=>0),//0
          'ee' => array('name' =>'拥抱每一天', 'prefix'=>$prefix['32'],'day'=>0),//0
          'bf' => array('name' =>'幸福满家园', 'prefix'=>$prefix['32'],'day'=>6),//6 7
          'ws' => array('name' =>'长夜的牵引', 'prefix'=>$prefix['32'],'day'=>0),//0
          'be' => array('name' =>'真道分解', 'prefix'=>$prefix['32'],'day'=>0),//0
          'tr' => array('name' =>'彩虹桥', 'prefix'=>$prefix['32'],'day'=>0),//0
          'ns' => array('name' =>'生命的四季', 'prefix'=>$prefix['32'],'day'=>5),
          'cw' => array('name' =>'齐来颂扬', 'prefix'=>$prefix['32'],'day'=>5),

          // '' => '',
          // 'bv' => '',
          // 'bv' => '空中辅导',
          // 
          // 
          // 'bv' => '无愧的工人',
          // 'bv' => '有问必答',
          // 'bv' => '生命指南针',
          // 'bv' => '蓝天绿洲',
          // 'bv' => '圣乐天地 ',
          // 'bv' => '好牧人',
          // 'bv' => '善牧良言',
          // 'bv' => '经动人心',
          // 'bv' => '信仰百宝箱',
          // 'bv' => '生命的福音',
          // 'bv' => '听听女人心',
          // 'bv' => '生根建造',
          // 'bv' => '聆听主道',
          // 'bv' => '圣言盛宴',
          // 'bv' => '真理之光',
          // 'bv' => '圣乐天地 - 古典圣诗',
          // 'bv' => '空中崇拜',
          // 'bv' => '给力人生',
          // 'bv' => '空中门训',
          // 'bv' => '生活之光',

          // 'nissigz3' = array(
          //  // 训练节目-适合事奉人员
          //  // 接棒人
          //  // 晨曦讲座
          //  // 申命记
          //  // 教牧辅导
          //  // 事奉装备
          //  // 基督教教义
          //  // 基督教伦理学
          //  // 圣诞节特辑
          //  // 新约神学
          //  ),

        );
      
      
      foreach ($radio_list_simple as $key => $programs) {
        $menu['31'] = "【i r】i-radio爱广播
【eg】英语世界
【g t】恩典与真理
【wa】天路导向
【bg】普世佳音
【yu】绝妙当家
【gv】生活无国界
【zz】零点零距离
【se】恋爱季节
【up】亲情不断电
【bc】书香园地
【gn】现代人的希望
【hg】欢乐卡恰碰
【yn】爱在人间（云南）
【im】i关怀心磁场
【i b】无限飞行号
【r t】今夜心未眠
【em】听听90后
【y r】Yi-radio爱广播".$notice ;
        $menu['32'] = '【bv】灵命日粮
【ee】拥抱每一天
【b f】幸福满家园
【ws】长夜的牵引'.$notice ;
        // foreach ($programs as $key2 => $value2) {
        //   $menu["$key"] .= "\n【".$key2."】". $value2;
        // }
        if($keyword == $key) {
          $wechatObj->text($menu["$keyword"])->reply();
          return;
        }
      }
      // bv-1;
      if(in_array($keyword, array_keys($radios_list)) || in_array(substr($keyword, 0,2), array_keys($radios_list)) ) { // || in_array($keyword, $value2)
        $offset = 0;
        if(strlen($keyword)>2){
          $offset = substr($keyword, 3,1);
          $keyword = substr($keyword, 0,2);
          watchdog('offset', $offset, array(), WATCHDOG_NOTICE, 'link');
        }
        if($radios_list[$keyword]['day'] == 0) {//1-7
          $title = $radios_list[$keyword]['name'];//'英语世界';
          $week_day = date('N', time());
          $title = "【".$keyword."】".$title;
          $string = date('ymd',time()-$offset*24*60*60);
          // $musicurl = // http://liangyou2.nissigz.com:15200/gv/gv131218.mp3
          $musicurl = $radios_list[$keyword]['prefix'].$keyword."/".$keyword.$string.'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新".date("n月d日-周").$week_day;
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          return;
        }
        if($radios_list[$keyword]['day'] == 5) {//1-5
          $desc = '1-5';
          $title = $radios_list[$keyword]['name'];//'英语世界';
          $week_day = date('N', time()-$offset*24*60*60);
          $title = "【".$keyword."】".$title;
          $string = date('ymd',time());
          $num = $radios_list[$keyword]['day'];
          if($week_day>5) {
            $week_day = date('N', time());
            $tus = date('d')+($num - $week_day);
            $string = date('ym',time()).$tus;
          }
          $musicurl = $radios_list[$keyword]['prefix'].$keyword."/".$keyword.$string.'.mp3';
          $desc = "love_yongbuzhixi 公众号，每日更新".date("n月d日-周一到周五播出");
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          return;
        }
        if($radios_list[$keyword]['day'] == 6) {//6 7
          $desc = '6,7';
          $title = $radios_list[$keyword]['name'];//'英语世界';
          $week_day = date('N', time()-$offset*24*60*60);
          $title = "【".$keyword."】".$title;
          $string = date('ymd',time());
          if($week_day/2) {
            $week_day = date('N', time());
            $tus = date('d')+(6 - $week_day);
            $string = date('ym',time()).$tus;
          }else{            
            $week_day = date('N', time());
            $tus = date('d')+(7 - $week_day);
            $string = date('ym',time()).$tus;
          }
          $musicurl = $radios_list[$keyword]['prefix'].$keyword."/".$keyword.$string.'.mp3';
          $desc = "love_yongbuzhixi 公众号，每日更新".date("n月d日-周6周日播出");
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          return;
        }
        if($radios_list[$keyword]['day'] == 1 || $radios_list[$keyword]['day'] == 2) {
          $title = $radios_list[$keyword]['name'];//'英语世界';
          $week_day = date('N', time()-$offset*24*60*60);
          $title = "【".$keyword."】".$title;
          $week_day = date('N', time());
          $num = $radios_list[$keyword]['day'];
          $tus = date('d')+($num - $week_day);
          $string = date('ym',time()).$tus;
          // $musicurl = // http://liangyou2.nissigz.com:15200/gv/gv131218.mp3
          $musicurl = $radios_list[$keyword]['prefix'].$keyword."/".$keyword.$string.'.mp3';
          $desc = "love_yongbuzhixi 公众号，每日更新".date("n月d日-周$num 播出");
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          return;
        }

      }

      switch ($keyword) {
        case '00':     
          $contentStr = $notice;//."\n此期间,可访问指令为\n【52】今日广播\n【523】在天父怀中";//广播指令为纯数字，请勿带*号。号和中括号\n【1】玩法介绍\n【2】发布相片/心情\n【3】查看活跃用户\n【4】每日灵修广播\n
            mp_service_update_user_info($wechatObj);
          break;        
        case '88':     
          $contentStr = "指令已取消！\n【1】玩法介绍\n【2】发布相片/心情\n【3】查看活跃用户\n【4】好牧人灵修广播\n【5】良友今日广播";
          if($uid) 
            mp_service_update_cmd('88',$FromUserName);
          break;
        case '1':
          $contentStr ="通过微信玩转永不止息？\n如果您是永不止息会员，\n回复【9】绑定后更多玩法\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【5010】灵命日粮文字版\n回复【110】推荐帮助-如何推荐给好友？\n回复【365】恩典365";
            mp_service_update_user_info($wechatObj);
          break;
        case '2':
          $contentStr = "表达爱的心语,遥寄未来的TA!\n【20】发布照片\n【201】无主情话\n【202】时光隧道\n【203】独居生活\n【204】想对你说\n回复获得更详细发布说明\n 回复【00】返回主菜单\n回复【5】进入良友广播";
            mp_service_update_user_info($wechatObj);
          // 【201】无主情话(随便说点情话)-38
          // 【202】时光隧道(分享我的过去)-39
          // 【203】独居生活(记录现在的生活)-40
          // 【204】想对你说(写给喜欢的人)-41
          break;
        case '20':
          // if(!$uid) {
          //   $contentStr = "您还没有与网站帐号绑定！暂时不能发相片！\n回复【9】查看绑定帮助";
          // }else
          {
            $contentStr = "请选择您要发布的相片\n(15秒内发送)\n";
            db_update('mp_service')
              ->fields(array(
                'last_cmd' => '20',
                'last_cmd_timestamp' => REQUEST_TIME,
              ))
              ->condition('uid', $uid)
              ->execute();
          }
          break;
        case '201':
          $contentStr = "(随便说点情话)请回复:【201+内容】\n比如：201今天天气好，心情不错，未来的你呢？\n即可发布【无主情话】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
            mp_service_update_user_info($wechatObj);
          break;

        case '202':
          $contentStr = "(分享我的过去)请回复:【202+内容】\n比如：202记得大三那年，还没到夏至，我在湖边的操场上～\n即可发布【时光隧道】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
            mp_service_update_user_info($wechatObj);
          break;

        case '203':
          $contentStr = "(记录现在的生活)请回复:【203+内容】\n比如：203明天开始，要去丰台跑市场了\n即可发布【独居生活】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
            mp_service_update_user_info($wechatObj);
          break;

        case '204':
          $contentStr = "(写给喜欢的人)请回复:【204+内容】\n比如：204这个世界很浮躁，内心的需要早已被人们忽略掉！\n即可发布【想对你说】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
            mp_service_update_user_info($wechatObj);
          break;
        case '3':
          $contentStr =  "最近活跃的弟兄姊妹有：\n\t\t侯星光\n\t\t韩富军\n\t\t王露\n\t\t畅卢涛...\n\n回复【00】进入主菜单\n回复【5】进入良友广播\n 本功能测试开发中～";
            mp_service_update_user_info($wechatObj);
          break;
        case '4':
        case '6':
        case '8':
          $contentStr =  "本菜单开发中\n回复【00】进入主菜单\n回复【5】良友广播\n";
          mp_service_update_user_info($wechatObj);
          break;
        case '7':
          $title = 'FM 77.7-love_yongbuzhixi';
          $musicurl = 'http://fm77.u.qiniudn.com/fm11.mp3';
          $desc = "云上的爱";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case 'm':
          $title = '每日箴言-'.date('md');
          $musicurl = 'http://www.chinesetodays.org/Portals/11/'.date('M').'Devos/'.date('j').'14.mp3';
          $desc = 'love_yongbuzhixi公众号';;
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '77':
          $title = 'FM 77.7-love_yongbuzhixi';
          $musicurl = 'http://fm77.u.qiniudn.com/77/wodeaiybb.mp3';
          $desc = "我的爱不改变";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '5': 
        case '51':
        case '53':
          $contentStr =  "【500】长夜的牵引\n【501】灵命日粮\n【502】拥抱每一天\n【503】恋爱季节*new*\n【504】幸福满家园^\n【505】亲情不断电*\n【506】欢乐卡洽碰\n【507】书香园地*\n【508】ds晨曦讲座\n 【509】生活无国界\n注意：广播指令为纯数字\n【528】每日读经\n【9010】推荐给好友\n【52】进入下一页\n".$notice;//【501-1】昨日节目/调皮
          // break;    
          // $contentStr =  "【500】长夜的牵引\n【501】灵命日粮\n【502】拥抱每一天\n【503】恋爱季节*new*\n【504】幸福满家园^\n【505】亲情不断电*\n【506】欢乐卡洽碰\n【507】书香园地*\n【508】ds晨曦讲座\n 【509】生活无国界\n注意：广播指令为纯数字\n【528】每日读经\n【9010】推荐给好友\n【52】进入下一页";//【501-1】昨日节目/调皮
          // break; 
          // // $contentStr =  $notice;//【510】无限飞行号\n 【511】i-radio爱广播^\n【512】i关怀心磁场\n【513】真理之光\n回复【5】进入上一页\n回复【00】进入主菜单\n带*节目为周一到周五\n带^节目为15分钟\n回复【110】推荐给好友\n【365】恩典365*new*\n
          // break;

          // $contentStr =  $notice;//【530】绝妙当家\n【531】彩虹桥\n【532】现代人的希望\n回复【00】进入主菜单\n回复【5】返回上级菜单\n回复【110】推荐给好友\n【365】恩典365*new*\n
          break;
        case '52':
          $contentStr =  "【520】喜乐的心\n【521】荒漠甘泉乐侣\n【522】静夜亮光\n【523】在天父怀中\n【5010】灵命日粮\n【525】真道分解\n【526】祷告良辰*new*\n【527】每周一歌*new*\n【528】每日读经*new*\n".$notice;//回复【5】返回上级菜单\n【365】恩典365*new*\n【524】灵命日粮\n
          break;
        case '9':
          $contentStr =  "注意：此功能为http://yongbuzhixi.com会员才可以使用\n回复【900 个人邮箱 姓名】申请内测 注意中间空格\n就要绑定，请回复\n【91昵称?手机后四位】 \n》比如：91活水泉?1407\n》91后面的为您的昵称。\n》昵称后面的？号不能少哦！\n【900】如何查看用户昵称\n【901】如何查看手机信息\n【5】进入良友广播\n";
          break;
        case '900':
          $contentStr =  "Q:如何查看用户昵称？\n A:登录http://yongbuzhxi.com查看。\n回复【900 个人邮箱 姓名】申请内测\n注意中间空格\n【9】返回绑定菜单\n【00】返回主菜单\n【5】进入良友广播\n";
            mp_service_update_user_info($wechatObj);
          break;
        case '901':
          $contentStr =  "Q:如何查看手机信息？\n A:注册的时候填写的\n如果在注册时没有填写，您可以到个人页面，点击：编辑->基本信息。\n回复【900 个人邮箱 姓名】申请内测,注意中间空格\n回复【9】返回绑定菜单\n回复【00】返回主菜单\n回复【5】进入良友广播\n";
            mp_service_update_user_info($wechatObj);
          break;
        case '119':
          $contentStr =  "请加个人帐号：yongbuzhixi_love与我们更进一步交流\n把您使用到的问题发给我们\n回复【00】返回主菜单\n回复【5】进入良友广播";
            mp_service_update_user_info($wechatObj);
          break;
        case '911':
          $contentStr =  "立即回复【900 个人邮箱 姓名】申请双11活动参与资格！\n回复【5】进入良友广播";
          break;
        case 'Y':
        case 'y':
          $contentStr =  "谢谢反馈！";
          break;
        case 'N':
        case 'n':
          $contentStr =  "谢谢反馈！";
          break;
          // $img = array(
          //     'Title'=> '第一天 爱是恒久忍耐',
          //     'Description'=>'',
          //     'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
          //     'Url'=>'http://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5MzQ3OTA2MA%3D%3D&appmsgid=10000311&itemidx=1&sign=68ba37452de8968121010831e3f45d43&scene=1#wechat_redirect'
          //   );
          // $news[] = $img;
        case '365':
          $html = file_get_html('http://v.tudou.com/_114352882/');
          //get title $('[code]').attr('code')
          $Title = trim($html->find('[code]', 0)->plaintext);
          $Title = str_replace('查看','',$Title);
          $Url =' http://www.tudou.com/programs/view/'.$html->find('[code]', 0)->attr['code'];
          $Description = "温馨提醒：注意流量!!！\n欢迎分享转发到朋友圈。\n\n另招募恩典365义工团队，听写当日的内容，供那些没有流量的弟兄姊妹阅读，如果您有感动，请加小永微信：yongbuzhixi_love回复【366】了解详情\n每日回复【365】获取更新";
          $img = array(
            'Title'=> $Title,
            'Description'=>$Description,
            'PicUrl'=>"http://t1.baidu.com/it/u=2408335515,2522544091&fm=23&gp=0.jpg",
            'Url'=> $Url
          );
          $news[] = $img;         
          $wechatObj->news($news)->reply();
          break;
        case '366':
          $Title = "恩典365文字义工团队招募";
          $Url ='http://wx.dev.camplus.hk/node/371';
          $Description = "亲爱的主内佳人，\n
      小永向您及您的家人致以新年的问候！在新的一年里，小永祝福您与主更亲近，每一天与主同行，恩上加恩。\n
不知道您是否收看过【寇绍恩】牧师的【恩典365】，如果您方便每天上网，而且有WIFI的话，那么祝福你，希望您能每天拿出5分钟来灵修，与神相交。\n
      然而，在我们享受这么美好祝福的时候，有相当多一部分弟兄姊妹，他们没时间上网，他们没有WIFI，少的可怜的流量，然后他们的生命需要喂养，所以，小永号召大家一起组织一个文字义工团队，大家把听写的内容发布到博客上，小永再通过微信发给弟兄姊妹。\n
团队组成：
    听写组
    校对组
听写组成员，根据时间，自由领取当日节目任务，完成后发布到网站上，校对组进行核对。小永给义工成员协助编辑权限即可。

希望大家在蒙受祝福的同时，也让别人得福，赶快来报名参加吧！\n
详情请咨询小永，微信号：yongbuzhixi_love";
          $img = array(
            'Title'=> $Title,
            'Description'=>$Description,
            'PicUrl'=>"http://wx.dev.camplus.hk/sites/default/files/grace365/Screenshot_2014-01-15-20-04-16.png",
            'Url'=> $Url
          );
          $news[] = $img;         
          $wechatObj->news($news)->reply();
          break;
        case '114':
        case '40':
          // $contentStr =  "必须回复911+至少一句感恩的话(5个字)\n才可以得到今天的炼爱哦！\n回复【5】进入良友广播";
          $img = array(
              'Title'=> '第18天 爱寻求理解',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/18'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '第17天 爱提升亲密',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/17'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '第16天 爱是为他祷告',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/16'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '第15天 爱是敬重对方',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/15'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '第14天 爱是公平地争吵',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/14'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '第13天 爱是公平地争吵',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/13'
            );
          // $news[] = $img;
          // $contentStr =  "必须回复911+至少一句感恩的话(5个字)\n才可以得到今天的炼爱哦！\n回复【5】进入良友广播";
          $img = array(
              'Title'=> '第12天 爱是谦让',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/12'
            );
          // $news[] = $img;
           $img = array(
              'Title'=> '第11天 爱是珍惜',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/11'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第10天 爱是无条件的',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/10'
            );
          // $news[] = $img;
           $img = array(
              'Title'=> '第9天 爱是制造好印象',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/09'
            );
          // $news[] = $img;
           $img = array(
              'Title'=> '第8天 爱是不嫉妒',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/08'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第7天 爱相信最美好的',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/07'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第6天 爱是不轻易动怒',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/06'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第5天 爱是不粗鲁',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/05'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第4天 爱是恩慈',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/04'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第3天 爱是不自私',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/03'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第2天 爱是恩慈',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/02'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '第1天 爱是恒久忍耐',
              'Description'=>'',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/love40/01'
            );
          // $news[] = $img;
          $img = array(
              'Title'=> '《炼爱》序言-我们的心灵渴望爱，就象我们的身体需要氧气',
              'PicUrl'=>'http://love.yongbuzhixi.org/sites/default/files/love40/s4568837.jpg',
              'Url'=>'http://love.yongbuzhixi.org/node/15'
            );
            $news[] = $img;  

          // $img = array(
          //   'Title'=>'用手机，登录【永不止息】^_^',
          //   'Description'=>'单图文 标题15字 摘要60字',
          //   'PicUrl'=>'http://www.yongbuzhixi.com/sites/default/files/pictures/picture-172-1356487827.jpg',
          //   'Url'=>'http://yongbuzhixi.com'
          // );
          //单图文 标题15字 摘要60字
          //多图文 1标题16字 2标题15字
          $wechatObj->news($news)->reply();
          break;
        case '110':
          // $html = file_get_html('http://pp2717153.weixin.pp.cc/18817_mini.html');
          // $items = $html->find('#links', 0);
          // foreach ($items->children as $key => $html) {
          //   $link = $html->find('a', 0);
          //   $Url = $link->attr['href'];
          //   $Title = trim($html->find('h2', 0)->plaintext);
          //   $Description = trim($html->find('p', 0)->plaintext);

          //   $picture = $html->find('img', 0);
          //   $PicUrl = $picture->attr['src'];
          //   $img = array(
          //     'Title'=> $Title,
          //     'Description'=>$Description,
          //     'PicUrl'=>$PicUrl,
          //     'Url'=>$Url
          //   );
          //   $news[] = $img; 
          // }
          $img = array(
              'Title'=> '关于永不止息',
              'Description'=>'你良友的啥关系？',
              'PicUrl'=>'http://www.yongbuzhixi.com/sites/all/themes/love/family_1.png',
              'Url'=>'http://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5ODQ4NjU4MA==&appmsgid=10000220&itemidx=2&sign=62a8888bdb56bc268f255c020e024434'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '▌如何推荐给好友？',
              'Description'=>'转给你的好友吧',
              'PicUrl'=>'',//http://www.yongbuzhixi.com/sites/all/themes/love/family_2.png
              'Url'=>'http://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5ODQ4NjU4MA==&appmsgid=10000220&itemidx=2&sign=62a8888bdb56bc268f255c020e024434'
            );
            $news[] = $img;
          // $img = array(
          //   'Title'=>'用手机，登录【永不止息】^_^',
          //   'Description'=>'单图文 标题15字 摘要60字',
          //   'PicUrl'=>'http://www.yongbuzhixi.com/sites/default/files/pictures/picture-172-1356487827.jpg',
          //   'Url'=>'http://yongbuzhixi.com'
          // );
          //单图文 标题15字 摘要60字
          //多图文 1标题16字 2标题15字
          mp_service_update_user_info($wechatObj);
          $wechatObj->news($news)->reply();
          break;
         case '9010':
          $img = array(
              'Title'=> '玩转永不止息,良友一起来！',
              'Description'=>'永不止息时光机，会员尊贵待遇！',
              'PicUrl'=>'http://mmsns.qpic.cn/mmsns/0fV5QBhibUJh4BDj8puTVpBPibdMnlp7YYX5ibib87W7KACey1qpTmN0Rw/0.jpg',
              'Url'=>'http://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5ODQ4NjU4MA==&appmsgid=10000352&itemidx=1&sign=f99612d4cfd626d8649dbe6a59faff75#wechat_redirect'
            );
            $news[] = $img; 
          //单图文 标题15字 摘要60字
          //多图文 1标题16字 2标题15字
          mp_service_update_user_info($wechatObj);
          $wechatObj->news($news)->reply();
          break;
 
        case '5010':
        case '５０１０':
          // $title = '灵命日粮';
          $html = file_get_html('http://simplified-odb.org/');
          //get title
          $Title = trim($html->find('h1.entry-title', 0)->plaintext);
          // get body
          $Description = trim($html->find('.entry-content', 0)->plaintext);
          
          // Try to set your custom field
          $html = file_get_html('http://ya-mi.org/category/devotionals/odb/');
          $picture = $html->find('.homepost .thumb img', 0);

          $PicUrl = $picture->attr['src'];
          $img = array(
            'Title'=> $Title,
            'Description'=>$Description,
            'PicUrl'=>$PicUrl,
            'Url'=> 'http://simplified-odb.org'
          );
          $news[] = $img;
          $wechatObj->news($news)->reply();
          break;

        case '1':
          $title = "线路1测试";
          $musicurl = 'http://audio2.liangyou.net/files/media/program_live/gv/gv131218.mp3';
          //http://audio.liangyou.net/download.php?t=1&c=vmf&f=vmf131101.mp3
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '2':
          $title = "线路2测试";
          $musicurl = 'http://liangyou2.nissigz.com:15200/gv/gv131218.mp3';
          //http://audio.liangyou.net/download.php?t=1&c=vmf&f=vmf131101.mp3
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '500':
        case '５００':
          $title = "长夜的牵引";
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '524':
        case '501':
        case '５２４':
        case '５０１':
          $keyword = '501';
          $title = '灵命日粮';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '502':
        case '５０２':
          $keyword = '502';
          $title = '拥抱每一天';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '503':
        case '５０３':
          $keyword = '503';
          $title = '恋爱季节';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '504':
        case '５０４':
          $keyword = '504';
          $title = '幸福满家园';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;    
        case '505':
        case '５０５':
          $keyword = '505';
          $title = '亲情不断电';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号,周1-5";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '506':
        case '５０６':
          $title = '欢乐卡洽碰';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '507':
        case '５０７':
          $title = '书香园地';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号,周1-5";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '508':
        case '５０８':
          $title = '晨曦讲座';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '509':
        case '５０９':
          $title = '生活无国界';
          $title = "$title-".date('ymd');
          $musicurl = $prefix_uri."$radio_list[$keyword]/$radio_list[$keyword]".date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case 'wizbee':
          $title = 'wizbee试听';
          $desc = '外教一对一 Tandy';
          $musicurl = 'http://fm77.u.qiniudn.com/egTandy_01-13-14_joan.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;

        case '523':
        case '５２３':
          $title = '在天父怀中';
          $title = "$title".date('md');
          // $y = data('y')-1;
          $str = date('md');
          watchdog('$str', $str, array(), WATCHDOG_NOTICE, 'link');
          //http://audio1.liangyou.net/files/media/ly_daily/2013Daily_130114.mp3
          $musicurl = 'http://audio1.liangyou.net/files/media/ly_daily/2013Daily_13'.$str.'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '1224':
          $title = '耶稣全貌';
          $desc = '序言-love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-00.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122501':
          $title = '耶稣全貌-第一章 道成肉身';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-01.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122502':
          $title = '耶稣全貌-第二章 圣婴降生';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-02.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122503':
          $title = '耶稣全貌-第三章 预备道路';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-03.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122504':
          $title = '耶稣全貌--第四章 传道之始';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-04.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122505':
          $title = '耶稣全貌--第五章 知难而进';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-05.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122506':
          $title = '耶稣全貌--第六章 登山宝训';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-06.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122507':
          $title = '耶稣全貌--第七章  是非分明';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-07.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122508':
          $title = '耶稣全貌--第八章  命令风浪';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-08.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122509':
          $title = '耶稣全貌--第九章  五饼二鱼';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-09.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122510':
          $title = '耶稣全貌--第十章  荣耀显现';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-10.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122511':
          $title = '耶稣全貌--第11章';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-11.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '122512':
          $title = '耶稣全貌--第12章';
          $desc = 'love_yongbuzhixi公众号，每日更新';
          $musicurl = 'http://s3.amazonaws.com/ysqm/ch-12.mp3';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '1225':
              $img = array(
                  'Title'=> '良友串流广播【试听】',
                  'Description'=>'点击查看全文收听！回复【11+您的建议反馈内容】，回复1225给love_yongbuzhixi获取本消息！永不止息，需要有你！',
                  'PicUrl'=>'http://farm2.staticflickr.com/1275/4700591844_7010757842_b.jpg',
                  'Url'=>'http://stream.liangyou.net/channel/65837e3587'
                );
                $news[] = $img; 
            $wechatObj->news($news)->reply();
             break;
        case '520':
        case '５２０':
        // http://media.haomuren.org/dev/joy/joyhrt0716.mp3
          $title = '喜乐的心';
          $title = "$title-".date('ymd');
          $musicurl = 'http://media.haomuren.org/dev/joy/joyhrt'.date('md').'.mp3';
          // http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo130709.mp3
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;        
        case '521':
        // 荒漠甘泉乐侣
          $title = '荒漠甘泉乐侣-圣经广播网';
          $title = "$title";
          // $musicurl = 'http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo'.date('ymd').'.mp3';
          $musicurl = 'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C'.(date('N')-1).'SD.m4a';
          // http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo130709.mp3
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;          
        case '522':
        case '５２２':
          $title = '静夜亮光';
          $musicurl = 'http://media.haomuren.org/dev/ev/evn'.date('md').'.mp3';
          //http://media.haomuren.org/dev/ev/evn0709.mp3
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '525':
        case '５２５':
          $title = '真道分解';
          $title = "$title-".date('ymd');
          $musicurl = 'http://media.biblexpo.net/biblexpo/daily/Daily_'.date('ymd').'.mp3';
          $desc = "love_yongbuzhixi公众号，每日更新";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '526':
        case '５２６': 
          $title = '祷告良辰-圣经广播网';
          $title = "$title-".date('ymd');
          $musicurl = 'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C'.(date('N')-1).'PT.m4a';
          $desc = '周1-5love_yongbuzhixi公众号';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '527':
        case '５２７': 
          $title = '每周一歌-圣经广播网';
          $title = "$title-".date('ymd');
          $musicurl = 'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C'.(date('N')-1).'WS.m4a';
          $desc = 'love_yongbuzhixi公众号';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '528':
        case '５２８': 
          $title = '每日读经-圣经广播网';
          $title = "$title-".date('ymd');
          $musicurl = 'http://bbnradio.org.edgesuite.net/BBNOnDemand/chinese/C'.(date('N')-1).'DBR.m4a';
          $desc = 'love_yongbuzhixi公众号';
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case 'ee':
          $html = file_get_html('http://blog.sina.cn/dpool/blog/articlelist_1570453241.html');
          $items = $html->find('#pl-blog-list .cont-txt-tit-ls li');
          foreach ($items->children as $key => $html) {
            $link = $html->find('.pic-tit-lk', 0);
            $Url = $link->attr['href'];
            $Title = trim($html->find('h2', 0)->plaintext);
            $Description = trim($html->find('.desc', 0)->plaintext);

            $picture = $html->find('.pic', 0);
            $PicUrl = $picture->attr['data-img'];
            $img = array(
              'Title'=> $Title,
              'Description'=>$Description,
              'PicUrl'=>$PicUrl,
              'Url'=>$Url
            );
            $news[] = $img; 
          } 
          $wechatObj->news($news)->reply();
          break;
        default:
            $wechat_user_info = mp_service_update_user_info($wechatObj);
            if(substr($keyword, 0,2) == '91' && substr($keyword, 0,3) != '911') {
              $keyword = substr($keyword, 2);
              $keywords = explode('?', $keyword);
              if (!isset($keywords[1])) {
                $keywords = explode('？', $keyword);
              }
              if (!isset($keywords[1])) {
                $contentStr = "昵称后面缺少问号！\n回复【9】查看绑定帮助\n如需帮助，请回复【11+问题】";
              }else{
                $name = $keywords[0];
                if(strlen($keywords[1])!=4) {
                  $contentStr = "手机后四位信息【".$keywords[1]."】不正确！\n回复【9】查看绑定帮助\n如需帮助，请回复【11+问题】";
                  // break;
                }
                $error_msg = user_validate_name($name);
                if(strlen($error_msg)>0){
                  $contentStr = $error_msg;
                  // break;
                }
                $account = user_load_by_name($name);
                if(!$account) {
                  $contentStr = "不存在用户名【".$name."】！\n回复【9】查看绑定帮助\n如需帮助，请回复【11+问题】";
                  // break;
                }else {
                  $profile = profile2_load_by_user($account);
                  $tel = $profile['main']->field_telephone[LANGUAGE_NONE][0]['value'];
                  if(substr($tel, 7)!==$keywords[1]) {
                    $contentStr = "手机后四位信息【".$keywords[1]."】匹配不正确！\n回复【9】查看绑定帮助\n如需帮助，请回复【11+问题】";
                    // break;
                  }else {
                    //if bind,or not
                    $uid = mp_service_is_bind($account->uid);
                    if($uid) {
                      $contentStr = "用户名【".$account->name."】已绑定过！\n回复【9】查看绑定帮助\n如需帮助，请回复【11+问题】";
                      // break;
                    }else {
                      mp_service_bind_uid($FromUserName,$account->uid);
                      $contentStr = "恭喜您，【".$account->name."】绑定成功！！\n回复【00】进入主菜单";
                      // break;
                    }
                  }
                }
              } 
            }

            //  elseif (substr($keyword, 0,2) == '20') {
            // //201+您想说的话
            //   $menukey = substr($keyword, 0, 3);//201-204
            //   $keyword = substr($keyword, 3);
            //   if(strlen($keyword) < 10 ) {
            //     $contentStr = "内容不能少于10字！";
            //   }else{
            //     $uid = mp_service_get_uid_by_name($FromUserName);
            //     if(!$uid) {
            //       $contentStr = "您还没有与网站帐号绑定！\n回复【9】查看绑定帮助";
            //     }else{
            //       $node = new stdClass();
            //       $node->title = $keyword.'【来自微信】';
            //       $node->type = 'photo';
            //       node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
            //       $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
            //       $node->uid = $uid;
            //       $node->status = 1; //(1 or 0): published or not
            //       $node->promote = 0; //(1 or 0): promoted to front page
            //       $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
            //       $node->path['pathauto'] = false;
            //       // $node->body[$node->language][0]['value']   = $postObj->Content . print_r($postObj,true);
            //       // $node->body[$node->language][0]['summary'] = text_summary($postObj->Content);
            //       // $node->body[$node->language][0]['format']  = 'filtered_html';
            //       // 【201】无主情话(随便说点情话)-38
            //       // 【202】时光隧道(分享我的过去)-39
            //       // 【203】独居生活(记录现在的生活)-40
            //       // 【204】想对你说(写给喜欢的人)-41

            //       $node->field_status_topic[$node->language][0]['tid'] = $menukey-163;
            //       ////////begin @see love_layout_node_presave($node)
            //        // $pattern = '/#([^\\#|.]+)#|＃([^\\＃|.]+)＃/';
            //        // preg_match_all($pattern, $node->title, $matches, PREG_SET_ORDER);
            //        // $node->field_status_tags[LANGUAGE_NONE] = array();
            //        // foreach ($matches as $key => $value) {

            //        //    $term_name = $value[1];
            //        //    $term = taxonomy_get_term_by_name($term_name);
            //        //    //new one
            //        //    if(!count($term)){
            //        //     $term = new stdClass();
            //        //     $term->vid = 1;
            //        //     $term->name = $term_name;
            //        //     taxonomy_term_save($term);
            //        //     //$term = taxonomy_get_term_by_name($term_name);
            //        //     foreach ($term as $value) {
            //        //        //dpm($value,$key);
            //        //        $node->field_status_tags[LANGUAGE_NONE][$term->tid]['tid'] = $term->tid;
            //        //      }
            //        //    }else{
            //        //      foreach ($term as $tid => $value) {
            //        //        // dpm($value,$tid);
            //        //        $node->field_status_tags[LANGUAGE_NONE][$tid]['tid'] = $tid;
            //        //      }
            //        //    }
            //        // }
            //       ///////////end
            //       if($node = node_submit($node)) { // Prepare node for saving
            //           node_save($node);//\n".$tip."
            //           $contentStr = "恭喜您【".$keyword."】\n已经成功发布，查看已发布内容：http://www.yongbuzhixi.com";
            //       }
            //     }
            //   }
            //   # code...
            // } 

            elseif (substr($keyword, 0,2) == '11') {
            //201+您想说的话
              if(strlen($keyword) < 10 ) {
                $contentStr = "内容不能少于3字！";
              }else{
                $mp_service_records = mp_service_get_record($FromUserName);
                
                if($mp_service_records['last_cmd'] == '1111') {
                  $contentStr = "您今天已经参与过了，请明天再来吧！\n回复【31】听听广播吧！";
                }else{
                  mp_service_update_cmd('1111',$FromUserName);
                  ///////
                  $comment = new stdClass();

                  $comment->nid = 1; // nid of a node you want to attach a comment to
                  $comment->cid = 0; // leave it as is
                  $comment->pid = 0; // parent comment id, 0 if none 
                  $comment->uid = 0; // user's id, who left the comment
                  watchdog('mp_service123', '<pre>'.print_r($wechat_user_info,true), array(), WATCHDOG_NOTICE, 'link');
                  $comment->mail = $wechat_user_info['contact_info']['fake_id'].'@yongbuzhixi.com'; // user's email wechat_user_info
                  //a:10:{s:7:"fake_id";i:2553430760;s:9:"nick_name";s:6:"麦青";s:9:"user_name";s:10:"maiqing-py";s:9:"signature";s:31:"在心中修篱种菊..........";s:4:"city";s:6:"昆明";s:8:"province";s:6:"云南";s:7:"country";s:6:"中国";s:6:"gender";i:2;s:11:"remark_name";s:0:"";s:8:"group_id";i:108;}
                  $comment->name = $wechat_user_info['contact_info']['nick_name']; // If user is authenticated you can omit this field, it will be auto-populated, if the user is anonymous and you want to name him somehow, input his name here
                  // $comment->thread = '01/'; // OPTIONAL. If you need comments to be threaded you can fill this value. Otherwise omit it.
                  $comment->hostname = $_SERVER['REMOTE_ADDR'] ;// OPTIONAL. You can log poster's ip here
                  $comment->created = time(); // OPTIONAL. You can set any time you want here. Useful for backdated comments creation.
                  $comment->is_anonymous = 0; // leave it as is
                  $comment->homepage = ''; // you can add homepage URL here
                  $comment->status = COMMENT_PUBLISHED;//COMMENT_PUBLISHED; // We auto-publish this comment
                  $comment->language = LANGUAGE_NONE; // The same as for a node
                  $keyword = substr($keyword, 2);
                  $subject = truncate_utf8($keyword, 15, $wordsafe = FALSE, $add_ellipsis = FALSE, $min_wordsafe_length = 1);
                  $comment->subject = $subject.'【来自微信】'; 
                  
                  $comment->signature = $wechat_user_info['contact_info']['signature'] ;
                  
                  $comment->signature_format = 'filtered_html'; 
                  $comment->comment_body[$comment->language][0]['value'] = $keyword.'【来自微信】'; // Everything here is pretty much like with a node
                  $comment->comment_body[$comment->language][0]['format'] = 'filtered_html'; 
                  // $comment->field_custom_field_name[LANGUAGE_NONE][0]['value'] = 'Some value'; // OPTIONAL. If your comment has a custom field attached it can added as simple as this // preparing a comment for a save

                   // saving a comment
                  ///////////end
                  if($comment = comment_submit($comment)) { // Prepare node for saving                      
                      comment_save($comment);
                      $contentStr = "恭喜，发布成功,您是第".$comment->cid."位提意见者！\n地址：http://www.yongbuzhixi.com/ \n永不止息，需要有你！\nhttp://www.yongbuzhixi.com\n回复【31】听听广播吧！";
                  }
                }
              }
              # code...
            }elseif (substr($keyword, 0,6) == '201314') {
            //201+您想说的话
              if(strlen($keyword) < 10 ) {
                $contentStr = "内容不能少于3字！";
              }else{
                $mp_service_records = mp_service_get_record($FromUserName);
                
                if($mp_service_records['last_cmd'] == date('ymd')) {
                  $contentStr = "您今天已经参与过了，请明天再来吧！\n回复【31】听听广播吧！";
                }else{
                  mp_service_update_cmd(date('ymd'),$FromUserName);
                  ///////
                  $comment = new stdClass();

                  $comment->nid = 3; // nid of a node you want to attach a comment to
                  $comment->cid = 0; // leave it as is
                  $comment->pid = 0; // parent comment id, 0 if none 
                  $comment->uid = 0; // user's id, who left the comment
                  watchdog('mp_service123', '<pre>'.print_r($wechat_user_info,true), array(), WATCHDOG_NOTICE, 'link');
                  $comment->mail = $wechat_user_info['contact_info']['fake_id'].'@yongbuzhixi.com'; // user's email wechat_user_info
                  //a:10:{s:7:"fake_id";i:2553430760;s:9:"nick_name";s:6:"麦青";s:9:"user_name";s:10:"maiqing-py";s:9:"signature";s:31:"在心中修篱种菊..........";s:4:"city";s:6:"昆明";s:8:"province";s:6:"云南";s:7:"country";s:6:"中国";s:6:"gender";i:2;s:11:"remark_name";s:0:"";s:8:"group_id";i:108;}
                  $comment->name = $wechat_user_info['contact_info']['nick_name']; // If user is authenticated you can omit this field, it will be auto-populated, if the user is anonymous and you want to name him somehow, input his name here
                  // $comment->thread = '01/'; // OPTIONAL. If you need comments to be threaded you can fill this value. Otherwise omit it.
                  $comment->hostname = $_SERVER['REMOTE_ADDR'] ;// OPTIONAL. You can log poster's ip here
                  $comment->created = time(); // OPTIONAL. You can set any time you want here. Useful for backdated comments creation.
                  $comment->is_anonymous = 0; // leave it as is
                  $comment->homepage = ''; // you can add homepage URL here
                  $comment->status = COMMENT_PUBLISHED;//COMMENT_PUBLISHED; // We auto-publish this comment
                  $comment->language = LANGUAGE_NONE; // The same as for a node
                  $keyword = substr($keyword, 6);
                  $subject = truncate_utf8($keyword, 15, $wordsafe = FALSE, $add_ellipsis = FALSE, $min_wordsafe_length = 1);
                  $comment->subject = $subject.'【来自微信】'; 
                  
                  $comment->signature = $wechat_user_info['contact_info']['signature'] ;
                  
                  $comment->signature_format = 'filtered_html'; 
                  $comment->comment_body[$comment->language][0]['value'] = $keyword.'【来自微信】'; // Everything here is pretty much like with a node
                  $comment->comment_body[$comment->language][0]['format'] = 'filtered_html'; 
                  // $comment->field_custom_field_name[LANGUAGE_NONE][0]['value'] = 'Some value'; // OPTIONAL. If your comment has a custom field attached it can added as simple as this // preparing a comment for a save

                   // saving a comment
                  ///////////end
                  if($comment = comment_submit($comment)) { // Prepare node for saving                      
                      comment_save($comment);
                      $num = $comment->cid;
                      $num = $num -106;
                      $contentStr = "恭喜,您是第".$num."位发布者！\n<a href='http://love.dev.camplus.hk/node/3'>点击查看</a> \n永不止息，需要有你！";
                  }
                }
              }
              # code...
            } elseif (substr($keyword, 0,3) == '911') {
              // if(strlen($keyword)<6) {
              //    $contentStr =  "必须回复911+至少一句感恩的话(5个字)\n回复【5】进入良友广播";
              //  }else 
               {                
                $wechatObj->setFuncFlag(TRUE);

                $contentStr = "[Joyful]谢谢您的代祷！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n回复【365】恩典365*new*\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
               }
            }  elseif (substr($keyword, 0,3) == '119') {
              $wechatObj->setFuncFlag(TRUE);
              $contentStr = "[TearingUp][TearingUp][TearingUp]代祷暂时关闭，因为没人愿意加入~请先为我们代祷吧\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
            } elseif (substr($keyword, 0,3) == '900') {
              // $keyword = '900 gxk@mail.com name';
              $keywords = explode(' ', $keyword);
              if (!isset($keywords[2])) {
                 $contentStr = "内测申请格式不正确！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
              }elseif(!valid_email_address($keywords[1])){
                $contentStr = "邮箱不正确！\n回复【900 个人邮箱 姓名】申请内测,注意中间空格\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
              }elseif(isset(user_load_by_mail($keywords[1])->uid)){
                $contentStr = "该邮箱已注册！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
              }else{
                $wechatObj->setFuncFlag(TRUE);
                watchdog('119', '<pre>'.print_r($keywords,TRUE), array(), WATCHDOG_NOTICE, 'link');
                $contentStr = "内测申请已收到，管理员审核后，请耐心等待永不止息下一轮内测！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";                
              }
            } elseif (substr($keyword, 0,4) == '9010') {
              // $keyword = '9010?天空蔚蓝?bluesky_still';
              // watchdog('keyword', $keyword, array(), WATCHDOG_NOTICE, 'link');
              $keywords = preg_split("/[？?]+/",$keyword);//preg_split( "/(?|？)/", $keyword);
              if (isset($keywords[1])) {
                $error_msg = user_validate_name($keywords[1]);
                if(is_null($error_msg)){
                  $nickname =  $keywords[1];
                  $level = mp_service_get_user_level($FromUserName);
                  if($level != 0) {
                    $contentStr = "您已有昵称，请勿重复绑定！\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
                  }elseif(!mp_service_distinct_nickname($nickname)){
                    mp_service_bind_nickname($FromUserName,$nickname);
                    $contentStr = "恭喜您，【".$nickname."】绑定成功！！\n赶快回复【502-3】试试吧!\n如果您没有转发和推荐永不止息，小心查到你封号哦！\n回复【9010】分享推荐给好友还不晚哦！";                    
                  }else{                    
                    $contentStr = "该昵称已被使用！\n请尝试新的昵称，谢谢！\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
                  }
                }else {
                 $contentStr = "对不起，小夕还不能识别您的奇葩昵称！\n格式不正确！请确认输入格式为【9010?奇葩昵称】\n帮助:$error_msg\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";

                }
              }else{
                $wechatObj->setFuncFlag(TRUE);
                // watchdog('level_errors', '<pre>'.$keyword, array(), WATCHDOG_NOTICE, 'link');
                $contentStr = "对不起，格式不正确！\n请确认输入格式为【9010?奇葩昵称】\n回复【9010】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";                
              }
              // watchdog('contentStr', $contentStr, array(), WATCHDOG_NOTICE, 'link');
              $wechatObj->text($contentStr)->reply();
            } elseif(strlen($keyword) == 5) {
              $before = abs(strstr($keyword, '-'));
              if(!$before) $before = abs(strstr($keyword, '-'));
              $radio_cmd = substr($keyword, 0,3);
              $radio_list = array(
                '500' => 'ws',
                '501' => 'bv',
                '502' => 'ee',
                '503' => 'se',
                '504' => 'bf',
                '505' => 'up',
                '506' => 'hg',
                '507' => 'bc',
                '508' => 'ds',
                '509' => 'gv',
                '523' => 'gv',
                );
                $radio_name = array(
                  '500' => '长夜的牵引',
                  '501' => '灵命日粮',
                  '502' => '拥抱每一天',
                  '503' => '恋爱季节',
                  '504' => '幸福满家园',
                  '505' => '亲情不断电',
                  '506' => '欢乐卡洽碰',
                  '507' => '书香园地',
                  '508' => '晨曦讲座',
                  '509' => '生活无国界',
                  '523' => '在天父怀中',
                );

              // $level = mp_service_get_user_level($FromUserName);
              if(is_numeric($before) && is_numeric($radio_cmd) && in_array($radio_cmd, array_keys($radio_list))) {

                // if($before>1) {// && $level == 0
                //   $contentStr = "对不起，非会员只可以收听过去1天的节目。\n如何成为会员，回复【9010】3秒搞定会员。/调皮";
                //   $wechatObj->text($contentStr)->reply();
                //   return;
                // }
                if($before>5) {
                  $contentStr = "对不起，非会员暂时可以收听过去5天的节目。\n如何成为高级会员，敬请关注近期活动。/调皮";
                  $wechatObj->text($contentStr)->reply();
                  return;
                }
                $which = $radio_list[$radio_cmd];
                $string = date('ymd',time()-$before*24*60*60);
                $musicurl = 'http://audio2.liangyou.net/files/media/program_live/'.$which.'/'.$which.''.$string.'.mp3';
                if($radio_cmd == '523') {
                  $y = date('y')-1;
                  $string = $y.date('md',time()-$before*24*60*60);
                  $musicurl = 'http://audio1.liangyou.net/files/media/ly_daily/2013Daily_'.$string.'.mp3';
                }
                $desc = date('m.d',time()-$before*24*60*60);
                // $title = $which.$string;
                $title = $radio_name[$radio_cmd];
                $title = "$title$desc";
                $hgmusicurl = $musicurl;
                $desc = "love_yongbuzhixi关注获取每日更新";
                $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
              }else{
                $contentStr = 'error input!';
              }

            }else {
              $wechatObj->setFuncFlag(TRUE);
              $contentStr = $notice;
              //如需高级服务，请微信添加 yongbuzhixi_love\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【11+问题】获得帮助\n回复【110】推荐给好友？\n回复【11+您的祝福与感恩或建议内容】呼唤小永归来吧！\n永不止息，需要有你！\n官网：http://love.yongbuzhixi.org \n
            }
          break;
      }
      $wechatObj->text($contentStr)->reply();
      exit;
      break;
    case Wechat::MSGTYPE_EVENT:
      // watchdog('MSGTYPE_EVENT', 'MSGTYPE_EVENT', array(), WATCHDOG_NOTICE, 'link');
      // $wechatObj->text("欢迎关注[Smile],我们将不定期发送永不止息最新动态给您~\n通过微信玩转永不止息？\n回复【00】进入主菜单\n所有功能测试开发中～敬请期待！")->reply();
      //preg to get key_words
      $Event =  $wechatObj->getRev()->getRevEvent();
      if(is_array($Event)) {
        $FromUserName =  $wechatObj->getRev()->getRevFrom();
        
        $res = mp_service_get_record($FromUserName);
        if($res) return;

        if($Event['event'] == 'subscribe') {
          if(mp_service_get_record($FromUserName)) {
            $contentStr = "欢迎回来[Smile]\n永不止息，需要有你!\n通过微信玩转永不止息？\n回复【00】进入主菜单\n回复【31】收听广播\n广播指令为纯数字，请勿带特殊括号\n除广播内容外，所有功能测试开发中～敬请期待！";
            mp_service_resubscribe($FromUserName);
          }else {
            $contentStr = "欢迎关注[Smile]\n永不止息-主内婚恋网，是http://yongbuzhixi.com 旗下的微信公众帐号。该网站是@bluesky_still透过对当前教会单身肢体需求的看见，业余时间开发的针对主内肢体婚恋社交网站，通过简洁的关系建立渠道，熟人的推荐，舆论监督与指导，为肢体提供一个便捷互相了解、信实互动的社交平台。\n回复【31】收听良友广播\n广播指令为纯数字，请勿带特殊符号\n";//通过微信玩转永不止息？\n回复【00】进入主菜单\n
            mp_service_add_user($FromUserName);
          }
          mp_service_text_reply($contentStr);
        }elseif($Event['event'] == 'unsubscribe') {
          mp_service_unsubscribe($FromUserName);
          $contentStr = '怎么走了呢？';
        }
      }
      
      break;
    case Wechat::MSGTYPE_IMAGE:
      $FromUserName =  $wechatObj->getRev()->getRevFrom();
      $PicUrl =  $wechatObj->getRev()->getRevPic();
      $uid = mp_service_get_uid_by_name($FromUserName);
      watchdog('PicUrl'.$uid, $PicUrl, array(), WATCHDOG_NOTICE, 'link');
      if($uid) {
        $mp_service_records = mp_service_get_record($FromUserName);
        mp_service_update_cmd('image',$FromUserName);
          watchdog('1', 'message', array(), WATCHDOG_NOTICE, 'link');
        if($mp_service_records['last_cmd'] == '20' && (REQUEST_TIME - $mp_service_records['last_cmd_timestamp'] > 900)) {
          $contentStr = "指令已超时！\n请回复【2】查看帮助！";
          $wechatObj->text($contentStr)->reply();
          exit;
        }
        watchdog('2', 'message', array(), WATCHDOG_NOTICE, 'link');
        if((REQUEST_TIME - $mp_service_records['last_cmd_timestamp'] <= 900)) {
          watchdog('3', 'message', array(), WATCHDOG_NOTICE, 'link');
          if($mp_service_records['last_cmd'] != '20') {
            watchdog('5', 'message', array(), WATCHDOG_NOTICE, 'link');
            $contentStr = "您发的图片想干什么呢？!\n请回复【2】查看帮助！";
            $wechatObj->text($contentStr)->reply();
            exit;
          }else {
            $contentStr = "发布成功！\n30秒内可回复文字添加照片描述\n如：【我爱北京！】该功能开发中~请代祷！";
            $wechatObj->text($contentStr)->reply();
            $node = new stdClass();
            $node->title = '【来自微信】';
            $node->type = 'photo';
            node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
            $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
            $node->uid = $uid;
            $node->status = 1; //(1 or 0): published or not
            $node->promote = 0; //(1 or 0): promoted to front page
            $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
            $node->path['pathauto'] = FALSE;
            $node->body[LANGUAGE_NONE][0]['value'] = '【来自微信】';
            $node->language = LANGUAGE_NONE;

            $path = $PicUrl.'.jpg';
            $filetitle = 'wechat';
            $filename = 'wechat-'.$uid.'-'.date("y-m-d").'.jpg';
            watchdog('6', 'message', array(), WATCHDOG_NOTICE, 'link');
            $file_temp = file_get_contents($path);//photos/
            watchdog('7', 'message', array(), WATCHDOG_NOTICE, 'link');
            $file_temp = file_save_data($file_temp, 'public://photos/'.$uid.'/'.$filename, FILE_EXISTS_RENAME);
            watchdog('8', 'message', array(), WATCHDOG_NOTICE, 'link');

            $node->field_photo = array(
              'und' => array(
                0 => array(
                    'fid' => $file_temp->fid,
                    'filename' => $file_temp->filename,
                    'filemime' => $file_temp->filemime,
                    'uid' => $uid,
                    'uri' => $file_temp->uri,
                    'status' => 1
                )
              )
            );
            watchdog('$node->field_photo', '<pre>'.print_r($node->field_photo,TRUE), array(), WATCHDOG_NOTICE, 'link');
            // $node->nid = 1;
            node_save($node);
            watchdog('node_save', $node->nid, array(), WATCHDOG_NOTICE, 'link');
            exit;

            // $wechatObj->text($contentStr)->reply();
            // mp_service_imageReplyText($contentStr);
          }
        }else {
          watchdog('4', 'message', array(), WATCHDOG_NOTICE, 'link');
          $contentStr = "指令超时！\n请回复【2】查看帮助！";
          $wechatObj->text($contentStr)->reply();
          exit;
        }

      }else {
        $contentStr = "您还没有与网站帐号绑定！暂不能发送图片！\n回复【31】听听广播吧！";//回复【9】查看绑定帮助
        $wechatObj->text($contentStr)->reply();
        exit;
      }
      // $wechatObj->text("已收到您发送的图片！")->reply();
      break;
    default:
      $wechatObj->text("如需帮助，请回复【11+问题】\n".$notice)->reply();
  }
  return;



}

function mp_service_update_user_info($wechatObj) {
  $FromUserName = $wechatObj->getRev()->getRevFrom();
  $res = mp_service_get_record($FromUserName);
  // if($res['last_cmd'] == 'update_contact_info') return;
  module_load_include('inc', 'mp_service', 'config');  
  $options = array(
    'account'=>'love_yongbuzhixi',
    'password'=>'mjk5nj',
    'datapath'=>'/home/wwwroot/love.dev.camplus.hk/public_html/sites/all/modules/mp_service/data/cookie_',
      'debug'=>FALSE,
      'logcallback'=>'logdebug' 
  );
  // drupal_chmod('/home/wwwroot/love.dev.camplus.hk/public_html/sites/all/modules/mp_service/data/cookie_yongbuzhixi');
  $wechat = new Wechatext($options);
  //$wechat
  $data = array();
  if ($wechat->checkValid()) {    
    $getMsg = $wechat->getMsg($lastid=0,$offset=0,$perpage=5,$day=0,$today=0,$star=0) ;
    foreach ($getMsg as $key => $Msg) {
      if($Msg['content'] == $wechatObj->getRevContent()) {
        $fakeId = $Msg['fakeid'];
        $data = $wechat->getInfo($fakeId);

        watchdog('get user:', $FromUserName.'  '.$fakeId.'  '.$data['contact_info']['user_name'].'  '.$data['contact_info']['nick_name'].'  '.$wechatObj->getRevContent(), array(), WATCHDOG_NOTICE, 'link');
        // if(isset($data['groups']))unset($data['groups']);
        // if(isset($data['base_resp']))unset($data['base_resp']);        
        // watchdog('mp_service_user_data', '<pre>'.print_r($data,true), array(), WATCHDOG_NOTICE, 'link');

        db_update('mp_service')
          ->fields(array(
            'fakeid' => $fakeId,
            'wxid' =>  $data['contact_info']['user_name'],
            'wxnickname' => $data['contact_info']['nick_name'],
            'contact_info' => serialize($data['contact_info']),
            'last_cmd' => "update_contact_info",
            'last_cmd_timestamp' => REQUEST_TIME,
          ))
          ->condition('fromusername', $FromUserName)
          ->execute();               
      }
    }
  } else {
    watchdog('login error', "login error wx", array(), WATCHDOG_NOTICE, 'link');
  }      
  return $data; 
}

function mp_service_update($FromUserName,$filed,$value) {
        db_update('mp_service')
          ->fields(array(
            $filed => $value,
            'last_cmd_timestamp' => REQUEST_TIME,
          ))
          ->condition('fromusername', $FromUserName)
          ->execute();     
}

function mp_service_is_bind($uid) {
  $uid = db_query('SELECT uid FROM {mp_service} WHERE uid = :uid', array(':uid' => $uid))->fetchField();
  return $uid;
}
function mp_service_get_uid_by_name($FromUserName) {
  $uid = db_query('SELECT uid FROM {mp_service} WHERE fromusername = :fromusername', array(':fromusername' => $FromUserName))->fetchField();
  return $uid;
}

function mp_service_get_record($FromUserName) {
  $res = db_query('SELECT * FROM {mp_service} WHERE fromusername = :fromusername', array(':fromusername' => $FromUserName))->fetchAssoc();
  return $res;
}
/**
 * False mean you can bind!
 * or please choose another nickname!
 */
function mp_service_distinct_nickname($nickname) {
  $res = db_query('SELECT * FROM {mp_service} WHERE nickname = :nickname', array(':nickname' => $nickname))->fetchAssoc();
  return $res;
}

function mp_service_get_user_level($FromUserName) {
  $res = db_query('SELECT * FROM {mp_service} WHERE fromusername = :fromusername', array(':fromusername' => $FromUserName))->fetchAssoc();
  // if(isset($res->uid)) return 1;
  if($res['wxid']) return 2;
  if($res['nickname']) return 3;
  return 0;
}
function mp_service_get_nofakeid() {
  $res = db_query('SELECT * FROM {mp_service} WHERE fakeid = 0')->fetchAll();
  return (array)$res;
}
// and bind!
function mp_service_bind_nickname($FromUserName,$nickname) {
  db_update('mp_service')
    ->fields(array(
      'nickname' => $nickname,
      'last_cmd' => '201',
      'last_cmd_timestamp' => REQUEST_TIME,
    ))
    ->condition('fromusername', $FromUserName)
    ->execute();
}
// and bind!
function mp_service_bind_uid($FromUserName,$bindUid) {
  db_update('mp_service')
    ->fields(array(
      'uid' => $bindUid,
      'last_cmd' => '91bind',
      'last_cmd_timestamp' => REQUEST_TIME,
    ))
    ->condition('fromusername', $FromUserName)
    ->execute();
}
// and a wechat user!
function mp_service_add_user($FromUserName,$last_cmd='subscribe') {
  db_insert('mp_service')
    ->fields(array(
      'fromusername' => $FromUserName,
      'last_cmd' => $last_cmd,
      'unsubscribe' => 0,
      'last_cmd_timestamp' => REQUEST_TIME,
      'created' => REQUEST_TIME,
    ))
    ->execute();
}
function mp_service_unsubscribe($FromUserName) {
  db_update('mp_service')
    ->fields(array(
      'unsubscribe' => 1,
      'last_cmd' => 'unsubscribe',
      'last_cmd_timestamp' => REQUEST_TIME,
    ))
    ->condition('fromusername', $FromUserName)
    ->execute();
}
function mp_service_resubscribe($FromUserName) {
  db_update('mp_service')
    ->fields(array(
      'unsubscribe' => 0,
      'last_cmd' => 'resubscribe',
      'last_cmd_timestamp' => REQUEST_TIME,
    ))
    ->condition('fromusername', $FromUserName)
    ->execute();
}
function mp_service_text_reply($contentStr='error~') {
  $postStr = $GLOBALS["HTTP_RAW_POST_DATA"];
  if (!empty($postStr)) {
    $postObj = simplexml_load_string($postStr, 'SimpleXMLElement', LIBXML_NOCDATA);
    // watchdog('mp-postObj', print_r($postObj,true), array(), WATCHDOG_NOTICE, 'link');
    //focus::SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1372159280 [MsgType] => event [Event] => subscribe [EventKey] => SimpleXMLElement Object ( ) )
    //receive::SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1372158829 [MsgType] => text [Content] => 看来 [MsgId] => 5893377295572656705 )
    $fromUsername = $postObj->FromUserName;
    $toUsername = $postObj->ToUserName;
    $keyword = trim($postObj->Content);
    $time = time();
    $textTpl = "<xml>
    <ToUserName><![CDATA[%s]]></ToUserName>
    <FromUserName><![CDATA[%s]]></FromUserName>
    <CreateTime>%s</CreateTime>
    <MsgType><![CDATA[%s]]></MsgType>
    <Content><![CDATA[%s]]></Content>
    <FuncFlag>0</FuncFlag>
    </xml>";   
    //subscribe begin我们将不定期发送永不止息最新动态给您~\n
    // if($postObj->MsgType == 'event' && $postObj->Event == 'subscribe') {
      
    // }
    // $contentStr = "欢迎关注[Smile]\n通过微信玩转永不止息？\n回复【00】进入主菜单\n回复【5】收听良友广播\n广播指令为纯数字，请勿带特殊括号\n除广播内容外，所有功能测试开发中～敬请期待！";
    $msgType = "text";
    $resultStr = sprintf($textTpl, $fromUsername, $toUsername, $time, $msgType, $contentStr);
    echo $resultStr;
    exit;

  }
}

function mp_service_imageReplyText($contentStr) {
  $postStr = $GLOBALS["HTTP_RAW_POST_DATA"];
  if (!empty($postStr)) {
    $postObj = simplexml_load_string($postStr, 'SimpleXMLElement', LIBXML_NOCDATA);
    watchdog('mp-postObj', print_r($postObj,true), array(), WATCHDOG_NOTICE, 'link');
    //SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1373499701 [MsgType] => image [PicUrl] => http://mmsns.qpic.cn/mmsns/ibiaMxQQytPZMjFUuLqe8eT1xibKw3apkMXqmCxqqTpmkGZQg7CnWoI5Q/0 [MsgId] => 5899136296960779666 [MediaId] => Gq6h5ZYJWPFtJkLuwryl5GNJOAdvnbwXOJFRGwItZbds_tHfNTxY3_x1A88f5vcd )
    $fromUsername = $postObj->FromUserName;
    $toUsername = $postObj->ToUserName;
    //
    $time = time();
    $textTpl = "<xml>
    <ToUserName><![CDATA[%s]]></ToUserName>
    <FromUserName><![CDATA[%s]]></FromUserName>
    <CreateTime>%s</CreateTime>
    <MsgType><![CDATA[%s]]></MsgType>
    <Content><![CDATA[%s]]></Content>
    <FuncFlag>0</FuncFlag>
    </xml>";
    if($postObj->MsgType == 'image') {
      $msgType = "text";
      $resultStr = sprintf($textTpl, $fromUsername, $toUsername, $time, $msgType, $contentStr);
      echo $resultStr;
      exit;
    }
  }
}

function mp_service_update_cmd($last_cmd,$FromUserName) {
  db_update('mp_service')
    ->fields(array(
      'last_cmd' => $last_cmd,
      'last_cmd_timestamp' => REQUEST_TIME,
    ))
    ->condition('fromusername', $FromUserName)
    ->execute();
}

// 福音节目-适合所有人士
// i-radio爱广播
// 英语世界
// 恩典与真理
// 天路导向
// 天路导向（粤）
// 普世佳音
// 绝妙当家
// 生活无国界
// 零点零距离
// 恋爱季节
// 亲情不断电
// 书香园地
// 现代人的希望
// 欢乐卡恰碰
// 爱在人间（云南）
// i 关怀心磁场
// 无限飞行号
// 今夜心未眠
// 听听90后
// Yi-radio爱广播
// 栽培节目-适合基督徒
// 灵命日粮
// 生命的四季
// 真道分解
// 空中辅导
// 幸福满家园
// 拥抱每一天
// 彩虹桥
// 齐来颂扬
// 无愧的工人
// 有问必答
// 生命指南针
// 蓝天绿洲
// 圣乐天地 
// 好牧人
// 善牧良言
// 经动人心
// 信仰百宝箱
// 长夜的牵引
// 生命的福音
// 听听女人心
// 生根建造
// 聆听主道
// 圣言盛宴
// 真理之光
// 圣乐天地 - 古典圣诗
// 空中崇拜
// 给力人生
// 空中门训
// 生活之光
// 训练节目-适合事奉人员
// 接棒人
// 晨曦讲座
// 申命记
// 教牧辅导
// 事奉装备
// 基督教教义
// 基督教伦理学
// 圣诞节特辑
// 新约神学

//http://www.wxhow.com/wxapi/?WX_GH=gh_ebdb3a74fdf6&plugin=bible&action=nissigz&title=%E8%89%AF%E5%8F%8B%E7%94%B5%E5%8F%B0&WX_GH_USER=ojC2PjnIwbEjowjfo20uhwsNRfvY
// 良友圣经学院

// 基础课程
// 探访事工
// 婚姻与家庭
// 初信造就
// 耶稣生平
// 基本研经法
// 旧约浅说
// 基要真理
// 本科文凭课程
// 基督教教义
// 基督教与科学
// 团队事奉
// 进深文凭课程
// 释经与讲道
// 崇拜学
// 中级讲道学
// 无神论与信仰
// 耶稣的神迹
// 基督化家庭
// 婚姻辅导
// 末世论
// 圣经概论
// 书信详解

//http://www.jiduzhijia.com/yinpin/tllc/index.htm
//http://www.jiduzhijia.com/book/madl.htm